name: semantic-release

# Run the workflow when a Pull Request is opened or when changes are pushed to master
on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Fetch the latest commit
      - name: Checkout
        uses: actions/checkout@v2

      # Setup Node.js using the appropriate version
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      # Install package dependencies
      - name: Install
        run: npm ci

      # Run tests
      - name: Test
        run: npm test

  release:
    # Only release on push to master
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    # Waits for test jobs to complete
    needs: [test]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install
        run: npm ci

      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
