name: Shellcheck

on: [pull_request]

jobs:
  shellcheck:
    name: check shell scripts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run ShellCheck
        run: ./shellcheck-check-shell-script.sh
