name: shellcheck

on: [pull_request]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run ShellCheck
        run: ./shellcheck.sh
